CREATE VIEW VW_TABLE_CREATE AS 
SELECT
'CREATE TABLE ['+TABLE_NAME+'] ( '+
STRING_AGG('['+cast(COLUMN_NAME as varchar(max)) +'] '+
CASE
WHEN UPPER(DATA_TYPE) IN ('BIGINT','INT') THEN 'NUMERIC'
WHEN UPPER(DATA_TYPE) IN ('XML','JSON') THEN 'VARCHAR'
ELSE UPPER(DATA_TYPE)
END
+
IIF (NUMERIC_PRECISION IS NOT NULL,' ('+CAST(NUMERIC_PRECISION AS VARCHAR(10))+','+CAST(NUMERIC_SCALE AS VARCHAR(10))+')',
IIF(CHARACTER_MAXIMUM_LENGTH IS NULL,'',
' ('+IIF(CHARACTER_MAXIMUM_LENGTH<0,'MAX',CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(10)))+')'))
, ',')+');' AS RESULT
FROM INFORMATION_SCHEMA.COLUMNS
GROUP BY TABLE_NAME;